[package]
name = "duct"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.13", features = ["json"] }
anyhow = "1.0"
duct-cli = {path = "../duct-cli/"}
duct-network = {path = "../duct-network/"}
