[package]
name = "duct-network"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
hyper = { version = "1.8.1", features = ["full"] }
hyper-util = { version = "0.1.20", features = ["full"] }
http = "1.4.0"
http-body-util = "0.1"
tokio-native-tls = "0.3"
native-tls = "0.2"
async-trait = "0.1.89"
anyhow = "1.0"
